services:

  # MySQL (REQUIRED)
  db:
    image: mysql:8.0
    container_name: booking_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: local_home_services_booking
      MYSQL_USER: booking_user
      MYSQL_PASSWORD: secret123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - booking_network

  # phpMyAdmin (OPTIONAL UI for MySQL)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: booking_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root123
    depends_on:
      - db
    networks:
      - booking_network

  # Redis (REQUIRED if using cache/session/queue)
  redis:
    image: redis:7-alpine
    container_name: booking_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - booking_network

  # Laravel Backend
  backend:
    build:
      context: ./backend
    container_name: booking_backend
    restart: unless-stopped
    ports:
      - "8088:8000"
    environment:
      DB_HOST: db
      DB_DATABASE: local_home_services_booking
      DB_USERNAME: booking_user
      DB_PASSWORD: secret123

      REDIS_HOST: redis
    depends_on:
      - db
      - redis
    networks:
      - booking_network

  # Frontend
  frontend:
    build:
      context: ./frontend
    container_name: booking_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - booking_network

volumes:
  mysql_data:
  redis_data:

networks:
  booking_network:
    driver: bridge