#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);


foreach (glob(__DIR__ . "/database/seeders/*.php") as $file) {
    require_once $file;
}

$command = $argv[1] ?? null;

if ($command === 'db:seed') {

    $class = $argv[2] ?? 'DatabaseSeeder';

    $seeder = new $class($mysqli);
    $seeder->run();

    echo "🌱 Done\n";

} else {
    echo "Usage:\n";
    echo "php artisan.php db:seed\n";
}
